Repository UnBArqDsw2022-1/2022_1_G5_SerFit, pull requests merged in 2022-07, with the labels that each got.

#56 Diagrama de Componentes
  docs/Modelagem/Estatica/DiagramaDeComponentes.md
  docs/_sidebar.md
  docs/assets/diagramaComponentes/Diagrama de Componentes.drawio.png
  docs/assets/diagramaComponentes/component-symbol.jpg
  docs/assets/diagramaComponentes/dependency-symbol.jpg
  docs/assets/diagramaComponentes/interface-symbol.jpg
  docs/assets/diagramaComponentes/port-symbol.jpg
  docs/index.html
Labels: documentation, enhancement

#75 #71 - Elaboração do CANVAS
  docs/Modelagem/Canvas.md
  docs/_sidebar.md
  docs/assets/canvas/Business Model Canvas.jpg
Labels: documentation

#63 57 diagrama de estados
  docs/Modelagem/DiagramaDeEstados.md
  docs/_sidebar.md
  docs/assets/modelagem/diagramaDeEstados/Diagrama1.svg
  docs/assets/modelagem/diagramaDeEstados/Diagrama2.svg
  docs/assets/modelagem/diagramaDeEstados/conjuncao.svg
  docs/assets/modelagem/diagramaDeEstados/estado.svg
  docs/assets/modelagem/diagramaDeEstados/estado_final.svg
  docs/assets/modelagem/diagramaDeEstados/inicio.svg
  docs/assets/modelagem/diagramaDeEstados/pseudo_escolha.svg
  docs/assets/modelagem/diagramaDeEstados/transicao.svg
Labels: documentation

#65 #64 adding EAP document
  docs/Base/ProjetoNaoOrientado/Extra/EAP.md
  docs/_sidebar.md
  docs/assets/EAP/wbs.jpeg
Labels: documentation

#79 55 casos de uso
  docs/Base/ProjetoNaoOrientado/CasosdeUso.md
  docs/Base/ProjetoNaoOrientado/GuiaDeEstilo.md
  docs/Base/Requisistos/Modelagem/CasosdeUso.md
  docs/_sidebar.md
  docs/assets/casosdeuso/CasosDeUso1.jpeg
  docs/assets/casosdeuso/CasosDeUso2.jpeg
  docs/assets/casosdeuso/CasosDeUso3.jpeg
Labels: documentation

#84 #83 - Criação do Diagrama de Sequência
  docs/Modelagem/DiagramasDinamicos/DiagramaDeSequencia.md
  docs/assets/diagrama-de-comunicacao/navegacao_cliente.png
  docs/assets/diagrama-de-comunicacao/navegacao_personal.png
  docs/assets/diagrama-de-sequencia/Sequence-diagram.png
Labels: documentation

#82 #43 - Diagrama de Tecnologias
  docs/Modelagem/DiagramasDinamicos/DiagramaDeTecnologias.md
  docs/assets/diagrama-de-tecnologias/Express.png
Labels: documentation

#85 42 correcoes entrega2 ffinal
  docs/Modelagem/DiagramasDinamicos/DiagramaDeAtividades.md
  docs/Modelagem/DiagramasDinamicos/DiagramaDeComunicacao.md
  docs/Modelagem/DiagramasDinamicos/DiagramaDeEstados.md
  docs/Modelagem/DiagramasDinamicos/DiagramaDeSequencia.md
  docs/Modelagem/DiagramasEstaticos/DiagramaDeClasses.md
  docs/Modelagem/DiagramasEstaticos/DiagramaDeComponentes.md
  docs/Modelagem/IniciativasExtras/Canvas.md
  docs/Modelagem/IniciativasExtras/CasosdeUso.md
  docs/Modelagem/IniciativasExtras/DiagramaDeTecnologias.md
  docs/Modelagem/IniciativasExtras/GuiaDeEstilo.md
  docs/_sidebar.md
Labels: bug, documentation, help wanted

#86 83 diagrama de sequencia
  docs/Modelagem/DiagramasDinamicos/DiagramaDeComunicacao.md
  docs/Modelagem/DiagramasDinamicos/DiagramaDeSequencia.md
  docs/Modelagem/IniciativasExtras/CasosdeUso.md
  docs/Modelagem/IniciativasExtras/DiagramaDeTecnologias.md
  docs/_sidebar.md
  docs/assets/diagrama-de-comunicacao/navegacao_cliente.jpeg
  docs/assets/diagrama-de-comunicacao/navegacao_cliente.png
  docs/assets/diagrama-de-comunicacao/navegacao_personal.jpeg
  docs/assets/diagrama-de-comunicacao/navegacao_personal.png
  docs/assets/diagrama-de-sequencia/Sequence-diagram.png
Labels: bug, documentation

#87 83-diagrama-de-sequencia
  docs/Modelagem/DiagramasDinamicos/DiagramaDeSequencia.md
Labels: bug, documentation
