Repository UnBArqDsw2022-1/2022_1_G5_SerFit, pull requests merged in 2022-06, with the labels that each got.

#4 Members card
  .github/.gitmessage
  docs/Base/Metodologias/BPMN.md
  docs/Base/Metodologias/Metodologias.md
  docs/Base/ProjetoNaoOrientado/DesignSprint.md
  docs/_DocTemplate.md
  members.html
Labels: documentation

#22 Resolve #14 - causa e efeito doc
  docs/_sidebar.md
  docs/assets/causaefeito/Cause_And_Effect _PROJ.svg
  docs/assets/causaefeito/Cause_And_Effect_BAD_PRODUCT.svg
  docs/assets/causaefeito/Cause_And_Effect_PROFISS.svg
  docs/assets/causaefeito/Cause_And_Effect_USER.svg
  docs/pages/Base/ProjetoNaoOrientado/CausaEfeito.md
Labels: documentation

#34 28 tap termo de abertura do projeto
  docs/_sidebar.md
  docs/pages/Base/ProjetoNaoOrientado/TAP.md
Labels: documentation, decision

#36 RichPicture Unificado
  docs/assets/drawio/RichPictureFinal.drawio
  docs/assets/richpicture/RichPictureFinal.png
  docs/pages/Base/Metodologias/RichPicture.md
Labels: documentation, enhancement

#29 Questionario
  docs/_sidebar.md
  docs/assets/questionario/respostasPergunta1.png
  docs/assets/questionario/respostasPergunta2.png
  docs/assets/questionario/respostasPergunta3.png
  docs/assets/questionario/respostasPergunta4.1.png
  docs/assets/questionario/respostasPergunta4.2.png
  docs/assets/questionario/respostasPergunta5.png
  docs/pages/Base/ProjetoNaoOrientado/Requisistos/Elicitacao/Questionario.md
Labels: documentation

#39 Analise de custo especificada
  docs/pages/Base/ProjetoNaoOrientado/TAP.md
Labels: documentation, enhancement
